#!/usr/bin/env python3
"""
Main aggregator script that combines all sources
"""
import sys
import subprocess
from datetime import datetime
from pathlib import Path


def run_scraper(script_name: str, args: list = None) -> str:
    """Run a scraper script and return its output"""
    cmd = ["python3", f"scripts/{script_name}"]
    if args:
        cmd.extend(args)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"Error running {script_name}: {e}", file=sys.stderr)
        print(f"stderr: {e.stderr}", file=sys.stderr)
        return f"# Error\n\nFailed to fetch data from {script_name}\n\n"


def generate_combined_report(report_type: str = "daily") -> str:
    """Generate a combined report from all sources"""
    args = ["--weekly"] if report_type == "weekly" else []

    print(f"Generating {report_type} report...", file=sys.stderr)

    # Header
    report = f"# DevOps Monitoring Digest - {report_type.title()}\n\n"
    report += f"*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}*\n\n"
    report += "---\n\n"

    # RSS Feeds
    print("Fetching RSS feeds...", file=sys.stderr)
    rss_content = run_scraper("rss_scraper.py", args)
    report += rss_content + "\n\n"

    # GitHub Releases
    print("Fetching GitHub releases...", file=sys.stderr)
    releases_content = run_scraper("github_releases.py", args)
    report += releases_content + "\n\n"

    # Hacker News
    print("Fetching Hacker News...", file=sys.stderr)
    hn_content = run_scraper("hacker_news.py", args)
    report += hn_content + "\n\n"

    # Footer
    report += "---\n\n"
    report += "*This report was automatically generated by Sentinel-Ops*\n"

    return report


def save_report(content: str, output_dir: str, filename: str):
    """Save report to file"""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    file_path = output_path / filename
    with open(file_path, 'w') as f:
        f.write(content)

    print(f"Report saved to: {file_path}", file=sys.stderr)
    return file_path


def main():
    """Main execution function"""
    # Determine report type
    report_type = "daily"
    if len(sys.argv) > 1:
        if sys.argv[1] == "--weekly":
            report_type = "weekly"
        elif sys.argv[1] == "--tri-daily":
            report_type = "tri-daily"

    # Generate report
    report = generate_combined_report(report_type)

    # Determine output path
    if report_type == "tri-daily":
        # For tri-daily, include time in filename
        date_str = datetime.now().strftime('%Y-%m-%d-%H%M')
        filename = f"digest-{date_str}.md"
    else:
        date_str = datetime.now().strftime('%Y-%m-%d')
        filename = f"digest-{date_str}.md"
    
    output_dir = f"output/{report_type}"

    # Save report
    save_report(report, output_dir, filename)

    # Also output to stdout for GitHub Actions
    print(report)

    return 0


if __name__ == "__main__":
    sys.exit(main())
